apiVersion: v1
kind: Service
metadata:
  name: kaf1
spec:
  type: LoadBalancer
  externalIPs:
    - 123.12.12.123
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka1
---
apiVersion: v1
kind: Service
metadata:
  name: kaf2
spec:
  type: LoadBalancer
  externalIPs:
    - 123.12.12.124
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka2